services:
  partner-openapi:
    image: TODO
    container_name: partner-openapi
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      # DB 설정
      DB_URL: ${DB_URL}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      # OpenTelemetry 설정
      OTEL_SERVICE_NAME: partner-openapi
      OTEL_RESOURCE_ATTRIBUTES: service.instance.id=partner-openapi
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_METRIC_EXPORT_INTERVAL: 30000
      OTEL_TRACES_SAMPLER: parentbased_traceidratio
      OTEL_TRACES_SAMPLER_ARG: 1
      OTEL_INSTRUMENTATION_MICROMETER_ENABLED: true
    restart: unless-stopped

  alloy:
    image: grafana/alloy
    container_name: partner-openapi-alloy
    ports:
      - "12345:12345"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_EXPORTER_LOKI_ENDPOINT: ${OTEL_EXPORTER_LOKI_ENDPOINT}
      OTEL_EXPORTER_PROMETHEUS_ENDPOINT: ${OTEL_EXPORTER_PROMETHEUS_ENDPOINT}
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    command: >
      run --server.http.listen-addr=0.0.0.0:12345
          --storage.path=/var/lib/alloy/data
          /etc/alloy/config.alloy
