spring.application.name: "goodpon-core-api"
spring.profiles.active: local

spring:
  config:
    import:
      - infra-db.yml
      - infra-redis.yml
      - infra-aws.yml
      - infra-security.yml
  web.resources.add-mappings: false

---
spring.config.activate.on-profile: local

server.port: 8081

client-host: http://localhost:5173

---
spring.config.activate.on-profile: prod

client-host: ${CLIENT_HOST}