services:
  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki:/etc/loki
      - loki-data:/loki
    command:
      - '--config.file=/etc/loki/loki.yml'
    restart:
      unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    restart:
      unless-stopped

  tempo:
    image: grafana/tempo
    container_name: tempo
    ports:
      - "3200:3200"
    volumes:
      - ./tempo:/etc/tempo
      - tempo-data:/var/tempo
    command:
      - '--config.file=/etc/tempo/tempo.yml'
    restart:
      unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=exemplar-storage'
      - '--enable-feature=native-histograms'
    restart:
      unless-stopped

volumes:
  loki-data:
  grafana-data:
  tempo-data:
  prometheus-data:
