spring.application.name: "partner-openapi"
spring.profiles.active: local

spring:
  config:
    import:
      - infra-db-jpa.yml
      - infra-db-flyway.yml
      - logging.yml

---
spring.config.activate.on-profile: local

server.port: 8081

---
spring.config.activate.on-profile: prod
