spring.application.name: partner-openapi
spring.profiles.active: local

server:
  tomcat:
    mbeanregistry:
      enabled: true

spring.config.import:
  - classpath:app-config/infra-db.yml

---
spring.config.activate.on-profile: local

server.port: 8081
