spring:
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      ssl:
        enabled: false
