auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki/data
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/data/boltdb-shipper-active
    cache_location: /loki/data/boltdb-shipper-cache
    resync_interval: 5m
  filesystem:
    directory: /loki/data/chunks

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      period: 24h

limits_config:
  ingestion_rate_mb: 20
  max_streams_per_user: 10000
  retention_period: 720h
  max_query_series: 1000
  max_query_look_back_triggered_by_alert: 720h