openapi: 3.0.1
info:
  title: Goodpon Partner OpenAPI
  description: Goodpon Partner OpenAPI Documentation
  version: 1.0.0
servers:
- url: http://localhost:8080
tags: []
paths: {}
components:
  schemas: {}
# @formatter:off
  securitySchemes:
    clientId:
      type: apiKey
      name: X-Goodpon-Client-Id
      in: header
      description: "가맹점 클라이언트 ID를 나타내는 HTTP 헤더"

    clientSecret:
      type: apiKey
      name: X-Goodpon-Client-Secret
      in: header
      description: "가맹점 클라이언트 시크릿을 나타내는 HTTP 헤더"

security:
  - clientId: []
  - clientSecret: []
# @formatter:on
