spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100

---
spring.config.activate.on-profile: local

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:local;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true

---
spring.config.activate.on-profile: test

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true

logging:
  level:
    org.springframework.orm.jpa: debug
    org.springframework.orm.transaction: debug
    org.hibernate.orm.jdbc.bind: trace

---
spring.config.activate.on-profile: local-dev

spring:
  jpa.properties.hibernate.connection.provider_disables_autocommit: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: partner-openapi-pool
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 0
      max-lifetime: 1200000 # 20 minutes
      connection-timeout: 30000 # 30 seconds
      validation-timeout: 5000 # 5 seconds
      leak-detection-threshold: 2000 # 2 seconds
      auto-commit: false

---
spring.config.activate.on-profile: prod

spring:
  jpa.properties.hibernate.connection.provider_disables_autocommit: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: partner-openapi-pool
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 0
      max-lifetime: 12000000 # 20 minutes
      connection-timeout: 30000 # 30 seconds
      validation-timeout: 5000 # 5 seconds
      leak-detection-threshold: 2000 # 2 seconds
      auto-commit: false
