services:
  partner-openapi:
    image: ${DOCKER_IMAGE}
    container_name: partner-openapi
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: prod
      # DB 설정
      DB_URL: ${DB_URL}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      # OpenTelemetry 설정
      OTEL_SERVICE_NAME: partner-openapi
      OTEL_RESOURCE_ATTRIBUTES: service.instance.id=partner-openapi
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://partner-openapi-alloy:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_METRIC_EXPORT_INTERVAL: 30000
      OTEL_TRACES_SAMPLER: parentbased_traceidratio
      OTEL_TRACES_SAMPLER_ARG: 0.1
      OTEL_INSTRUMENTATION_MICROMETER_ENABLED: true
    restart: unless-stopped
    networks:
      - partner-network

networks:
  partner-network:
    external: true
