services:
  valkey:
    image: valkey/valkey:8.0.1
    container_name: valkey
    volumes:
      - valkey-data:/data
    ports:
      - '6379:6379'
    restart: unless-stopped

  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goodpon
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
      TZ: Asia/Seoul
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  valkey-data:
  mysql-data: