services:
  valkey:
    image: valkey/valkey:8.0.1
    container_name: valkey
    volumes:
      - valkey-data:/data
    ports:
      - '6379:6379'
    restart: unless-stopped

volumes:
  valkey-data:
