services:
  dashboard-api:
    build:
      context: ../../modules/api/dashboard-api
      dockerfile: Dockerfile
    container_name: dashboard-api
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: local-dev
      # DB 설정
      DB_URL: ${DB_URL}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      # Redis 설정
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      # OpenTelemetry 설정
      OTEL_SERVICE_NAME: dashboard-api
      OTEL_RESOURCE_ATTRIBUTES: service.instance.id=dashboard-api
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://dashboard-api-alloy:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_METRIC_EXPORT_INTERVAL: 30000 # default 60초 -> 30초로 변경
      OTEL_TRACES_SAMPLER: parentbased_traceidratio
      OTEL_TRACES_SAMPLER_ARG: 0.1 # 10% 샘플링
      OTEL_INSTRUMENTATION_MICROMETER_ENABLED: true # Micrometer 사용
    restart: on-failure:3
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  dashboard-api-alloy:
    image: grafana/alloy
    container_name: dashboard-api-alloy
    ports:
      - '12345:12345'
    volumes:
      - ./dashboard-api/alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    command: >
      run --server.http.listen-addr=0.0.0.0:12345
          --storage.path=/var/lib/alloy/data
          /etc/alloy/config.alloy

  partner-openapi:
    build:
      context: ../../modules/api/partner-openapi
      dockerfile: Dockerfile
    container_name: partner-openapi
    ports:
      - '8081:8080'
    environment:
      SPRING_PROFILES_ACTIVE: local-dev
      # DB 설정
      DB_URL: ${DB_URL}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      # Redis 설정
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      # Kafka 설정
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      # OpenTelemetry 설정
      OTEL_SERVICE_NAME: partner-openapi
      OTEL_RESOURCE_ATTRIBUTES: service.instance.id=partner-openapi
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://partner-openapi-alloy:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_METRIC_EXPORT_INTERVAL: 30000
      OTEL_TRACES_SAMPLER: parentbased_traceidratio
      OTEL_TRACES_SAMPLER_ARG: 0.1
      OTEL_INSTRUMENTATION_MICROMETER_ENABLED: true
    restart: on-failure:3
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy

  partner-openapi-alloy:
    image: grafana/alloy
    container_name: partner-openapi-alloy
    ports:
      - '12346:12345'
    volumes:
      - ./partner-openapi/alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    command: >
      run --server.http.listen-addr=0.0.0.0:12345
          --storage.path=/var/lib/alloy/data
          /etc/alloy/config.alloy

  coupon-issuer-consumer:
    build:
      context: ../../modules/consumer/coupon-issuer-consumer
      dockerfile: Dockerfile
    container_name: coupon-issuer-consumer
    environment:
      SPRING_PROFILES_ACTIVE: local-dev
      # DB 설정
      DB_URL: ${DB_URL}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      # Redis 설정
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      # Kafka 설정
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      # OpenTelemetry 설정
      OTEL_SERVICE_NAME: coupon-issuer-consumer
      OTEL_RESOURCE_ATTRIBUTES: service.instance.id=coupon-issuer-consumer
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://coupon-issuer-consumer-alloy:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_METRIC_EXPORT_INTERVAL: 30000
      OTEL_TRACES_SAMPLER: parentbased_traceidratio
      OTEL_TRACES_SAMPLER_ARG: 0.1
      OTEL_INSTRUMENTATION_MICROMETER_ENABLED: true
    restart: on-failure:3
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy

  coupon-issuer-consumer-alloy:
    image: grafana/alloy
    container_name: coupon-issuer-consumer-alloy
    ports:
      - '12347:12345'
    volumes:
      - ./coupon-issuer-consumer/alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    command: >
      run --server.http.listen-addr=0.0.0.0:12345
          --storage.path=/var/lib/alloy/data
          /etc/alloy/config.alloy

  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./storage/mysql/init:/docker-entrypoint-initdb.d
      - ./storage/mysql/config:/etc/mysql/conf.d
      - ./storage/mysql/logs:/var/log/mysql
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "3306", "-uroot", "-p${DB_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysql-exporter
    ports:
      - "9104:9104"
    volumes:
      - ./storage/exporter/mysql/.my.cnf:/.my.cnf
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: valkey/valkey:8.0.1
    container_name: redis
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "valkey-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: redis:6379
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft 모드 필수 설정
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT

      # 리스너 및 광고 주소
      KAFKA_LISTENERS: INTERNAL://:29092,CONTROLLER://:29093,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # 클러스터 ID (고정값 또는 랜덤 생성해서 사용)
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      # 단일 브로커용 기본값
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    restart:
      unless-stopped
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092" ]
      interval: 1s
      timeout: 3s
      retries: 30

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8083:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki:/etc/loki
      - loki-data:/loki
    command:
      - '--config.file=/etc/loki/loki.yml'
    restart:
      unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    restart:
      unless-stopped

  tempo:
    image: grafana/tempo
    container_name: tempo
    ports:
      - "3200:3200"
    volumes:
      - ./monitoring/tempo:/etc/tempo
      - tempo-data:/var/tempo
    command:
      - '--config.file=/etc/tempo/tempo.yml'
    restart:
      unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=exemplar-storage'
      - '--enable-feature=native-histograms'
    restart:
      unless-stopped

volumes:
  mysql-data:
  redis-data:
  loki-data:
  grafana-data:
  tempo-data:
  prometheus-data:
