services:
  k6:
    image: grafana/k6:latest
    container_name: k6
    volumes:
      - ./k6-tests:/k6-tests
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://host.docker.internal:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM=true
    command: run /k6-tests/coupon-test.js -o experimental-prometheus-rw