info:
  description: |
    ### 인증 방식 (Authentication)

    API를 호출할 때는 반드시 아래의 HTTP 헤더를 포함해야 합니다. 이 정보는 요청을 인증하고, 클라이언트를 식별하는 데 사용됩니다.
    
    - **X-Goodpon-Client-Id**: 발급받은 상점의 클라이언트 ID ex) ck_f84532d22a4827c9e1f5328461d252b8
    - **X-Goodpon-Client-Secret**: 발급받은 상점의 클라이언트 시크릿 ex) sk_3e153d8453ea8bafb2604ee86f732652

    ### 멱등 요청 (Idempotent Request)

    쿠폰 발급, 사용, 사용 취소와 같은 POST 요청은 중복 요청을 방지하기 위해 멱등 키를 지정할 수 있습니다.  
    이 경우, 요청 헤더에 아래 값을 함께 포함해 주세요.

    - **Idempotency-Key**: 300자 이하의 고유한 문자열. 같은 작업을 여러 번 요청하더라도, 이 키를 통해 동일한 요청으로 인식됩니다.  
      단, 동일한 키로 요청할 경우 본문(payload)의 내용도 반드시 같아야 합니다.

    멱등 요청 시 발생할 수 있는 오류는 다음과 같습니다:

    - **400 Bad Request**: 멱등 요청에 필요한 **Idempotency-Key**가 누락되었거나 형식이 잘못된 경우
    - **409 Conflict**: 이전에 동일한 **Idempotency-Key**로 요청이 들어와 아직 처리 중인데, 또 같은 키로 요청이 들어온 경우
    - **422 Unprocessable Entity**: 이전 요청과 동일한 **Idempotency-Key**를 사용했지만, 본문(payload)의 내용이 다른 경우

    참고로, 시스템 내부 오류가 아닌 **비즈니스 로직 오류에 한해서만 멱등 요청으로 인정**됩니다.  
    즉, 시스템 예외가 발생한 경우에는 재요청이 동일한 결과를 보장하지 않을 수 있습니다.

    ### 응답에 Trace ID 포함

    모든 API 응답에는 **X-Goodpon-Trace-Id**라는 HTTP 헤더가 포함됩니다.  
    이 헤더는 요청을 고유하게 식별하며, 문제가 발생했을 때 디버깅이나 기술 지원을 위해 활용할 수 있습니다.

components:
  securitySchemes:
    clientId:
      type: apiKey
      name: X-Goodpon-Client-Id
      in: header
      description: "상점 클라이언트 ID를 나타내는 HTTP 헤더"

    clientSecret:
      type: apiKey
      name: X-Goodpon-Client-Secret
      in: header
      description: "상점 클라이언트 시크릿을 나타내는 HTTP 헤더"

    idempotencyKey:
      type: apiKey
      name: Idempotency-Key
      in: header
      description: "API 호출의 멱등성을 보장하기 위한 키. 중복 요청을 방지합니다."

security:
  - clientId: [ ]
  - clientSecret: [ ]
